import {css} from '@emotion/react'

export const dynamicCellContentAttr = (value: string) => css({[mq[0]]: {':before': { content: `"${value}"` }}})

export const mq = [`@media (max-width: ${760}px)`]

export const rowNumber = css({[mq[0]]: {':before': { content: `"Row number"` }}})
export const date = css({[mq[0]]: {':before': { content: `"Date"` }}})
export const refund = css({[mq[0]]: {':before': { content: `"Refund"` }}})
export const payable = css({[mq[0]]: {':before': { content: `"Payable"` }}})
export const taxYear = css({[mq[0]]: {':before': { content: `"Tax Year"` }}})
export const classOneDebt = css({[mq[0]]: {':before': { content: `"Class 1 Debt"` }}})
export const interestDue = css({[mq[0]]: {':before': { content: `"Interest Due"` }}})
export const from = css({[mq[0]]: {':before': { content: `"From"` }}})
export const rate = css({[mq[0]]: {':before': { content: `"Rate"` }}})
export const fromTo = css({[mq[0]]: {':before': { content: `"From/To"` }}})
export const earningsFactor = css({[mq[0]]: {':before': { content: `"Earnings factor"` }}})
export const maxWeeks = css({[mq[0]]: {':before': { content: `"Max weeks"` }}})
export const actualWeeks = css({[mq[0]]: {':before': { content: `"Actual weeks"` }}})
export const deficient = css({[mq[0]]: {':before': { content: `"Deficient"` }}})
export const selectPeriod = css({[mq[0]]: {':before': { content: `"Select period"` }}})
export const periodNumber = css({[mq[0]]: {':before': { content: `"Period No."` }}})
export const selectNICategoryLetter = css({[mq[0]]: {':before': { content: `"Select NI category letter"` }}})
export const enterGrossPay = css({[mq[0]]: {':before': { content: `"Enter gross pay"` }}})
export const employee = css({[mq[0]]: {':before': { content: `"Employee"` }}})
export const employer = css({[mq[0]]: {':before': { content: `"Employer"` }}})
export const total = css({[mq[0]]: {':before': { content: `"Total"` }}})
export const nameEmployer = css({[mq[0]]: {':before': { content: `"Name of employer"` }}})
export const grossPay = css({[mq[0]]: {':before': { content: `"Gross pay"` }}})
export const niCat = css({[mq[0]]: {':before': { content: `"NI category"` }}})
export const lel = css({[mq[0]]: {':before': { content: `"LEL"` }}})
export const lelPt = css({[mq[0]]: {':before': { content: `"LEL - PT"` }}})
export const ptUel = css({[mq[0]]: {':before': { content: `"PT - UEL"` }}})
export const employeeNics = css({[mq[0]]: {':before': { content: `"Employee NICS"` }}})
export const overUel = css({[mq[0]]: {':before': { content: `"Over UEL"` }}})
export const nicsNonCo = css({[mq[0]]: {':before': { content: `"NICS non-CO"` }}})
export const ifNotUd = css({[mq[0]]: {':before': { content: `"If not U/D"` }}})
export const netConts = css({[mq[0]]: {':before': { content: `"Net contributions"` }}})
export const employeeConts = css({[mq[0]]: {':before': { content: `"Employee contributions"` }}})
export const employerConts = css({[mq[0]]: {':before': { content: `"Employer contributions"` }}})
export const category = css({[mq[0]]: {':before': { content: `"Category"` }}})
