import {css} from '@emotion/react'

export const dynamicCellContentAttr = (value: string) => css({[mq[0]]: {':before': { content: `"${value}"` }}})

export const excludePrint = ['@media not print']
export const mq = [`@media (max-width: ${760}px)`]

export const rowNumber = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Row number"` }}}})
export const date = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Date"` }}}})
export const refund = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Refund"` }}}})
export const payable = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Interest"` }}}})
export const taxYear = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Tax Year"` }}}})
export const classOneDebt = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Class 1 Debt"` }}}})
export const interestDue = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Interest Due"` }}}})
export const from = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"From"` }}}})
export const rate = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Rate"` }}}})
export const fromTo = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"From/To"` }}}})
export const earningsFactor = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Earnings factor"` }}}})
export const maxWeeks = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Max weeks"` }}}})
export const actualWeeks = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Actual weeks"` }}}})
export const deficient = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Deficient"` }}}})
export const selectPeriod = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Select period"` }}}})
export const periodNumber = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Period No."` }}}})
export const selectNICategoryLetter = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Select NI category letter"` }}}})
export const enterGrossPay = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Enter gross pay"` }}}})
export const employee = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Employee"` }}}})
export const employer = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Employer"` }}}})
export const total = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Total"` }}}})
export const nameEmployer = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Name of employer"` }}}})
export const grossPay = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Gross pay"` }}}})
export const niCat = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"NI category"` }}}})
export const employeeNics = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Employee NICS"` }}}})
export const overUel = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Over UEL"` }}}})
export const nicsNonCo = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"NICS non-CO"` }}}})
export const ifNotUd = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"If not U/D"` }}}})
export const netConts = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Net contributions"` }}}})
export const employeeConts = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Employee contributions"` }}}})
export const employerConts = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Employer contributions"` }}}})
export const category = css({[excludePrint[0]]: { [mq[0]]: {':before': { content: `"Category"` }}}})
